name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install build dependencies
      run: npm install

    - name: Build release
      run: npm run build

    - name: Version number
      id: version_number
      run: echo "::set-output name=version::$(git describe --tags | sed s/^v//)"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version_number.outputs.version }}
        body: |
          ## Changelog

          ## Install Instructions
          - Click the `programmer_${{ steps.version_number.outputs.version }}.txt` link below to download the Programmer script.
          - Click the `sequencer_${{ steps.version_number.outputs.version }}.txt` link below to download the Sequencer script.
          - Click the `extractor_${{ steps.version_number.outputs.version }}.txt` link below to download the Extractor script.

          To install any of the scripts
          1. Open the file in the text editor.
          2. Copy the content of the file.
          3. In game, right click the programming board and select "Paste Lua configuration from clipboard" in the "Advanced" sub menu.

    - name: Upload release asset (programmer)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/programmer.txt
        asset_name: programmer_${{ steps.version_number.outputs.version }}.txt
        asset_content_type: text/json

    - name: Upload release asset (sequencer)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/sequencer.txt
        asset_name: sequencer_${{ steps.version_number.outputs.version }}.txt
        asset_content_type: text/json

    - name: Upload release asset (extractor)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/extractor.txt
        asset_name: extractor_${{ steps.version_number.outputs.version }}.txt
        asset_content_type: text/json